export enum Routes {
  HOME_SCREEN = 'HOME_SCREEN',
  LEFT_SCREEN = 'LEFT_SCREEN',
  RIGHT_SCREEN = 'RIGHT_SCREEN',
  TOP_SCREEN = 'TOP_SCREEN',
  BOTTOM_SCREEN = 'BOTTOM_SCREEN',
  SECOND_BOTTOM_SCREEN = 'SECOND_BOTTOM_SCREEN',
}
